### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by mcat-ee** [suyashkumar/smart-lights#5]
Hey!

Is there a feedback mechanism for if the switch is manually toggled? Or will the previous toggle state of the switch persist in the smart-light's state machine?

**Comment by suyashkumar** [comment]
Currently there is no feedback, however a feedback system using a potentiometer coupled to the axis of rotation should be able to serve that purpose! 

Currently the servo power is turned off when it's not moving, allowing the servo to move more "freely" but it's still not recommended to move it around much :).
